name: NewTools-Pharo9.0

on:
  push:
    branches: [ Pharo9.0 ]
  pull_request:
    branches: [ Pharo9.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        smalltalk: [ Pharo64-9.0 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalk.all.ston
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
#      - name: Coveralls GitHub Action
#        uses: coverallsapp/github-action@v1.1.1
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          # This name must be unique for each job
#          flag-name: ${{matrix.os}}-${{matrix.smalltalk}}
#          parallel: true
#  finish:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#    - name: Coveralls Finished
#      uses: coverallsapp/github-action@master
#      with:
#        github-token: ${{ secrets.github_token }}
#        parallel-finished: true
